version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: cirkulo-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cirkulo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cirkulo-network

  api:
    build: .
    container_name: cirkulo-api
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/cirkulo
      NODE_ENV: development
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    command: bun run dev
    networks:
      - cirkulo-network

volumes:
  postgres_data:

networks:
  cirkulo-network:
    driver: bridge
