import type { User } from "app/context/auth-context";
import type {
  Circle,
  FeedItem,
  UserStats,
  ContributionFeedItem,
  MilestoneFeedItem,
  MemberJoinedFeedItem,
  GoalCompletedFeedItem,
  CelebrationFeedItem,
} from "app/types/feed";

// Mock users
export const mockUsers: User[] = [
  { id: "user1", hasProfile: true, name: "Alex Chen" },
  { id: "user2", hasProfile: true, name: "Sarah Johnson" },
  { id: "user3", hasProfile: true, name: "Mike Rodriguez" },
  { id: "user4", hasProfile: true, name: "Emma Thompson" },
  { id: "user5", hasProfile: true, name: "David Kim" },
];

// Mock current user (logged in user)
export const mockCurrentUser: User = {
  id: "current-user",
  hasProfile: true,
  name: "Alex Chen",
  lensUsername: "alexchen",
  bio: "Saving for adventures and helping friends reach their goals. Passionate about community-driven finance and Bitcoin.",
};

// Mock circles (user's circles)
export const mockCircles: Circle[] = [
  {
    id: "circle1",
    name: "Beach Vacation Fund",
    emoji: "🏖️",
    description: "Saving for an amazing beach getaway with friends",
    savingType: "contribution",
    contributionSchedule: "weekly",
    endDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 90).toISOString(),
    goalName: "Beach Vacation",
    goalAmount: 5000,
    currentAmount: 2450,
    memberCount: 5,
    progress: 49,
    members: mockUsers,
    isPublic: true,
    category: "vacation",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 60).toISOString(),
    isActive: true,
  },
  {
    id: "circle2",
    name: "House Down Payment",
    emoji: "🏡",
    description: "Our first home together",
    savingType: "contribution",
    contributionSchedule: "monthly",
    endDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 365).toISOString(),
    goalName: "Down Payment",
    goalAmount: 50000,
    currentAmount: 15000,
    memberCount: 3,
    progress: 30,
    members: mockUsers.slice(0, 3),
    isPublic: false,
    category: "home",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 90).toISOString(),
    isActive: true,
  },
  {
    id: "circle3",
    name: "Gaming Setup",
    emoji: "🎮",
    description: "Building the ultimate gaming rig",
    savingType: "rotating",
    contributionSchedule: "bi-weekly",
    endDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 30).toISOString(),
    goalName: "Gaming PC",
    goalAmount: 3000,
    currentAmount: 2800,
    memberCount: 4,
    progress: 93,
    members: mockUsers.slice(0, 4),
    isPublic: true,
    category: "technology",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    isActive: true,
  },
];

// Mock public circles for explore page
export const mockPublicCircles: Circle[] = [
  ...mockCircles.filter((c) => c.isPublic),
  {
    id: "circle4",
    name: "European Adventure",
    emoji: "✈️",
    description: "Planning the ultimate European backpacking adventure",
    savingType: "contribution",
    contributionSchedule: "monthly",
    endDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 180).toISOString(),
    goalName: "Europe Trip",
    goalAmount: 8000,
    currentAmount: 6400,
    memberCount: 6,
    progress: 80,
    members: mockUsers.slice(0, 3),
    isPublic: true,
    category: "vacation",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 45).toISOString(),
    isActive: true,
  },
  {
    id: "circle5",
    name: "Master's Degree Fund",
    emoji: "🎓",
    description: "Investing in higher education for a better future",
    savingType: "contribution",
    contributionSchedule: "monthly",
    endDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 730).toISOString(),
    goalName: "Education",
    goalAmount: 25000,
    currentAmount: 8500,
    memberCount: 2,
    progress: 34,
    members: mockUsers.slice(0, 2),
    isPublic: true,
    category: "education",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 120).toISOString(),
    isActive: true,
  },
  {
    id: "circle6",
    name: "Wedding Celebration",
    emoji: "💍",
    description: "Making our dream wedding come true together",
    savingType: "contribution",
    contributionSchedule: "bi-weekly",
    endDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 365).toISOString(),
    goalName: "Dream Wedding",
    goalAmount: 15000,
    currentAmount: 12000,
    memberCount: 8,
    progress: 80,
    members: mockUsers.slice(0, 3),
    isPublic: true,
    category: "events",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 180).toISOString(),
    isActive: true,
  },
  {
    id: "circle7",
    name: "Youth Mentorship Program",
    emoji: "🎯",
    description: "Empowering the next generation through mentorship",
    savingType: "contribution",
    contributionSchedule: "monthly",
    endDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 60).toISOString(),
    goalName: "Program Development",
    goalAmount: 5000,
    currentAmount: 4650,
    memberCount: 19,
    progress: 93,
    members: mockUsers.slice(0, 3),
    isPublic: true,
    category: "education",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 25).toISOString(),
    isActive: true,
  },
  {
    id: "circle8",
    name: "Home Renovation",
    emoji: "🔨",
    description: "Transforming our kitchen into a modern space",
    savingType: "contribution",
    contributionSchedule: "monthly",
    endDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 365).toISOString(),
    goalName: "Kitchen Remodel",
    goalAmount: 30000,
    currentAmount: 9000,
    memberCount: 2,
    progress: 30,
    members: mockUsers.slice(0, 2),
    isPublic: true,
    category: "home",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 75).toISOString(),
    isActive: true,
  },
  {
    id: "circle9",
    name: "Community Garden Project",
    emoji: "🌱",
    description: "Growing fresh produce for our neighborhood",
    savingType: "contribution",
    contributionSchedule: "weekly",
    endDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 90).toISOString(),
    goalName: "Urban Garden Supplies",
    goalAmount: 3500,
    currentAmount: 2450,
    memberCount: 12,
    progress: 70,
    members: mockUsers.slice(0, 3),
    isPublic: true,
    category: "other",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 20).toISOString(),
    isActive: true,
  },
  {
    id: "circle10",
    name: "Tokyo Trip 2026",
    emoji: "🗾",
    description: "Experiencing the culture and cuisine of Japan",
    savingType: "contribution",
    contributionSchedule: "monthly",
    endDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 450).toISOString(),
    goalName: "Japan Vacation",
    goalAmount: 6000,
    currentAmount: 2100,
    memberCount: 4,
    progress: 35,
    members: mockUsers.slice(0, 3),
    isPublic: true,
    category: "vacation",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 40).toISOString(),
    isActive: true,
  },
  {
    id: "circle11",
    name: "Coding Bootcamp",
    emoji: "👨‍💻",
    description: "Learning to code and launch a tech career",
    savingType: "contribution",
    contributionSchedule: "monthly",
    endDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 180).toISOString(),
    goalName: "Career Training",
    goalAmount: 12000,
    currentAmount: 3600,
    memberCount: 2,
    progress: 30,
    members: mockUsers.slice(0, 2),
    isPublic: true,
    category: "education",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 55).toISOString(),
    isActive: true,
  },
  {
    id: "circle12",
    name: "Music Festival Squad",
    emoji: "🎵",
    description: "Rocking out together at the summer music festival",
    savingType: "contribution",
    contributionSchedule: "weekly",
    endDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 90).toISOString(),
    goalName: "Festival Tickets",
    goalAmount: 3000,
    currentAmount: 2700,
    memberCount: 10,
    progress: 90,
    members: mockUsers.slice(0, 3),
    isPublic: true,
    category: "events",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15).toISOString(),
    isActive: true,
  },
  {
    id: "circle13",
    name: "Community Center Renovation",
    emoji: "🏛️",
    description: "Restoring our local youth center for the community",
    savingType: "contribution",
    contributionSchedule: "monthly",
    endDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 120).toISOString(),
    goalName: "Youth Center Repairs",
    goalAmount: 8000,
    currentAmount: 3200,
    memberCount: 18,
    progress: 40,
    members: mockUsers.slice(0, 3),
    isPublic: true,
    category: "other",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    isActive: true,
  },
  {
    id: "circle14",
    name: "Local Animal Shelter",
    emoji: "🐕",
    description: "Supporting our furry friends in need",
    savingType: "contribution",
    contributionSchedule: "monthly",
    endDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 180).toISOString(),
    goalName: "Shelter Support Fund",
    goalAmount: 5000,
    currentAmount: 3750,
    memberCount: 25,
    progress: 75,
    members: mockUsers.slice(0, 3),
    isPublic: true,
    category: "other",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 35).toISOString(),
    isActive: true,
  },
  {
    id: "circle15",
    name: "School Supplies Drive",
    emoji: "✏️",
    description: "Helping students start the school year right",
    savingType: "contribution",
    contributionSchedule: "bi-weekly",
    endDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 60).toISOString(),
    goalName: "Back-to-School Donations",
    goalAmount: 2500,
    currentAmount: 2100,
    memberCount: 15,
    progress: 84,
    members: mockUsers.slice(0, 3),
    isPublic: true,
    category: "education",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 50).toISOString(),
    isActive: true,
  },
  {
    id: "circle16",
    name: "Youth Sports Program",
    emoji: "⚽",
    description: "Equipping our youth sports teams for success",
    savingType: "contribution",
    contributionSchedule: "monthly",
    endDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 90).toISOString(),
    goalName: "Equipment & Uniforms",
    goalAmount: 4000,
    currentAmount: 3800,
    memberCount: 22,
    progress: 95,
    members: mockUsers.slice(0, 3),
    isPublic: true,
    category: "other",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 12).toISOString(),
    isActive: true,
  },
  {
    id: "circle17",
    name: "Tree Planting Initiative",
    emoji: "🌳",
    description: "Creating a greener future for our city",
    savingType: "contribution",
    contributionSchedule: "monthly",
    endDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 180).toISOString(),
    goalName: "Urban Reforestation",
    goalAmount: 6000,
    currentAmount: 2400,
    memberCount: 31,
    progress: 40,
    members: mockUsers.slice(0, 3),
    isPublic: true,
    category: "other",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 22).toISOString(),
    isActive: true,
  },
  {
    id: "circle18",
    name: "Free Meal Program",
    emoji: "🍲",
    description: "Feeding our community with love and care",
    savingType: "contribution",
    contributionSchedule: "weekly",
    endDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 120).toISOString(),
    goalName: "Community Kitchen",
    goalAmount: 7500,
    currentAmount: 4500,
    memberCount: 28,
    progress: 60,
    members: mockUsers.slice(0, 3),
    isPublic: true,
    category: "other",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    isActive: true,
  },
  {
    id: "circle19",
    name: "Medical Fund for Friend",
    emoji: "💊",
    description: "Supporting our friend through their medical journey",
    savingType: "contribution",
    contributionSchedule: "bi-weekly",
    endDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 90).toISOString(),
    goalName: "Treatment Support",
    goalAmount: 10000,
    currentAmount: 7500,
    memberCount: 42,
    progress: 75,
    members: mockUsers.slice(0, 3),
    isPublic: true,
    category: "other",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 28).toISOString(),
    isActive: true,
  },
  {
    id: "circle20",
    name: "Local Library Books",
    emoji: "📚",
    description: "Building a wonderful children's library section",
    savingType: "contribution",
    contributionSchedule: "monthly",
    endDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 150).toISOString(),
    goalName: "Children's Section",
    goalAmount: 3000,
    currentAmount: 600,
    memberCount: 14,
    progress: 20,
    members: mockUsers.slice(0, 3),
    isPublic: true,
    category: "education",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
    isActive: true,
  },
];

// Mock user stats
export const mockUserStats: UserStats = {
  totalSaved: 2450,
  activeCircles: 3,
  goalsCompleted: 2,
  totalGoals: 5,
  monthlyTrend: 12,
};

// Mock streak data
export const mockStreak = {
  currentDays: 23,
  longestStreak: 45,
  lastContribution: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(), // 12 hours ago
};

// Mock profile activity feed
export const mockProfileActivity = [
  {
    id: "activity1",
    type: "contribution" as const,
    timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(), // 2h ago
    amount: 150,
    circle: mockCircles[0],
    reactions: [
      { user: mockUsers[1], emoji: "🔥" },
      { user: mockUsers[2], emoji: "💪" },
      { user: mockUsers[3], emoji: "👏" },
      { user: mockUsers[4], emoji: "🎉" },
      { user: mockUsers[0], emoji: "❤️" },
    ],
  },
  {
    id: "activity2",
    type: "milestone" as const,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(), // 1d ago
    circle: mockCircles[0],
    milestone: "50%",
    reactions: [
      { user: mockUsers[0], emoji: "🎉" },
      { user: mockUsers[2], emoji: "🔥" },
      { user: mockUsers[3], emoji: "💯" },
    ],
  },
  {
    id: "activity3",
    type: "contribution" as const,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(), // 2d ago
    amount: 200,
    circle: mockCircles[2],
    reactions: [
      { user: mockUsers[1], emoji: "🚀" },
      { user: mockUsers[4], emoji: "💪" },
    ],
  },
];

// Mock feed items
export const mockFeedItems: FeedItem[] = [
  {
    id: "feed1",
    type: "contribution",
    timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(), // 30 mins ago
    actor: mockUsers[0],
    circle: mockCircles[0],
    likeCount: 5,
    commentCount: 2,
    isLiked: false,
    amount: 150,
    currency: "$",
    message: "Keep it up! Almost halfway to our vacation goal.",
    circleProgress: {
      current: 2450,
      goal: 5000,
      percentage: 49,
    },
  } as ContributionFeedItem,
  {
    id: "feed2",
    type: "milestone",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(), // 2 hours ago
    actor: mockUsers[1],
    circle: mockCircles[0],
    likeCount: 12,
    commentCount: 8,
    isLiked: true,
    percentage: 50,
    amount: 2500,
    goalAmount: 5000,
    reactions: [
      { emoji: "🎉", count: 12, userReacted: true },
      { emoji: "🔥", count: 8, userReacted: false },
      { emoji: "❤️", count: 15, userReacted: true },
    ],
  } as MilestoneFeedItem,
  {
    id: "feed3",
    type: "member-joined",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(), // 5 hours ago
    actor: mockUsers[4],
    circle: mockCircles[1],
    likeCount: 3,
    commentCount: 1,
    isLiked: false,
    welcomeMessage: "Welcome to the circle! Let's achieve our savings goals together.",
  } as MemberJoinedFeedItem,
  {
    id: "feed4",
    type: "contribution",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(), // 8 hours ago
    actor: mockUsers[2],
    circle: mockCircles[2],
    likeCount: 7,
    commentCount: 3,
    isLiked: false,
    amount: 200,
    currency: "$",
    message: "So close to our gaming setup goal!",
    circleProgress: {
      current: 2800,
      goal: 3000,
      percentage: 93,
    },
  } as ContributionFeedItem,
  {
    id: "feed5",
    type: "goal-completed",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(), // 1 day ago
    actor: mockUsers[0],
    circle: {
      ...mockCircles[2],
      goalName: "Weekend Trip",
      goalAmount: 1500,
      currentAmount: 1500,
    },
    likeCount: 24,
    commentCount: 15,
    isLiked: true,
    totalSaved: 1500,
    daysToComplete: 45,
  } as GoalCompletedFeedItem,
  {
    id: "feed6",
    type: "contribution",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(), // 2 days ago
    actor: mockUsers[3],
    circle: mockCircles[1],
    likeCount: 4,
    commentCount: 1,
    isLiked: false,
    amount: 500,
    currency: "$",
    circleProgress: {
      current: 15000,
      goal: 50000,
      percentage: 30,
    },
  } as ContributionFeedItem,
  {
    id: "feed7",
    type: "celebration",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(), // 4 hours ago
    actor: mockUsers[1],
    circle: mockCircles[0],
    likeCount: 8,
    commentCount: 5,
    isLiked: false,
    content: "Just made my first contribution! Feels great to be saving with friends 🎉\n\nWho else is excited about our beach trip?",
    tags: ["SavingsGoals", "BeachBound", "TeamWork"],
  } as CelebrationFeedItem,
  {
    id: "feed8",
    type: "celebration",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(), // 12 hours ago
    actor: mockUsers[2],
    circle: mockCircles[0],
    likeCount: 15,
    commentCount: 9,
    isLiked: true,
    content: "Halfway there team! Let's keep the momentum going 💪\n\nI can already feel the sand between my toes!",
    imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
    imageAlt: "Beautiful beach with clear blue water and white sand",
    tags: ["HalfwayThere", "BeachVibes", "VacationMode"],
  } as CelebrationFeedItem,
  {
    id: "feed9",
    type: "celebration",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(), // 20 hours ago
    actor: mockUsers[4],
    circle: mockCircles[2],
    likeCount: 6,
    commentCount: 3,
    isLiked: false,
    content: "Who else is hyped for our gaming setup? Almost there! 🎮\n\nCan't wait to stream with the squad!",
    tags: ["GamingSquad", "AlmostThere"],
  } as CelebrationFeedItem,
  {
    id: "feed10",
    type: "celebration",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(), // 3 days ago
    actor: mockUsers[0],
    circle: mockCircles[1],
    likeCount: 11,
    commentCount: 7,
    isLiked: true,
    content: "Small wins add up! Every dollar counts 💰\n\nStaying consistent is the key to reaching our house down payment goal. Let's do this!",
    tags: ["ConsistencyIsKey", "SmallWins", "DreamHome"],
  } as CelebrationFeedItem,
];

// Mock circle activity feed (specific to circle detail page)
export const mockCircleActivity: FeedItem[] = [
  {
    id: "circle-activity-1",
    type: "contribution",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(), // 2h ago
    actor: mockUsers[0],
    circle: mockCircles[0],
    likeCount: 8,
    commentCount: 3,
    isLiked: true,
    amount: 150,
    currency: "$",
    message: "Keep it up! Almost halfway to our vacation goal.",
    circleProgress: {
      current: 2450,
      goal: 5000,
      percentage: 49,
    },
  } as ContributionFeedItem,
  {
    id: "circle-activity-2",
    type: "milestone",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(), // 6h ago
    actor: mockUsers[1],
    circle: mockCircles[0],
    likeCount: 15,
    commentCount: 12,
    isLiked: true,
    percentage: 50,
    amount: 2500,
    goalAmount: 5000,
    reactions: [
      { emoji: "🎉", count: 15, userReacted: true },
      { emoji: "🔥", count: 8, userReacted: false },
      { emoji: "❤️", count: 18, userReacted: true },
      { emoji: "💪", count: 5, userReacted: false },
    ],
  } as MilestoneFeedItem,
  {
    id: "circle-activity-3",
    type: "celebration",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(), // 12h ago
    actor: mockUsers[2],
    circle: mockCircles[0],
    likeCount: 12,
    commentCount: 7,
    isLiked: false,
    content: "Halfway there team! Let's keep the momentum going 💪\n\nI can already feel the sand between my toes!",
    imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
    imageAlt: "Beautiful beach with clear blue water and white sand",
    tags: ["HalfwayThere", "BeachVibes", "VacationMode"],
  } as CelebrationFeedItem,
  {
    id: "circle-activity-4",
    type: "contribution",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(), // 1d ago
    actor: mockUsers[1],
    circle: mockCircles[0],
    likeCount: 6,
    commentCount: 2,
    isLiked: false,
    amount: 200,
    currency: "$",
    message: "Double contribution this week! Let's do this!",
    circleProgress: {
      current: 2300,
      goal: 5000,
      percentage: 46,
    },
  } as ContributionFeedItem,
  {
    id: "circle-activity-5",
    type: "celebration",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(), // 1.5d ago
    actor: mockUsers[3],
    circle: mockCircles[0],
    likeCount: 9,
    commentCount: 4,
    isLiked: true,
    content: "Just made my first contribution! Feels great to be saving with friends 🎉\n\nWho else is excited about our beach trip?",
    tags: ["SavingsGoals", "BeachBound", "TeamWork"],
  } as CelebrationFeedItem,
  {
    id: "circle-activity-6",
    type: "member-joined",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(), // 2d ago
    actor: mockUsers[4],
    circle: mockCircles[0],
    likeCount: 4,
    commentCount: 2,
    isLiked: false,
    welcomeMessage: "Welcome to the circle! Let's achieve our savings goals together.",
  } as MemberJoinedFeedItem,
  {
    id: "circle-activity-7",
    type: "contribution",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(), // 3d ago
    actor: mockUsers[3],
    circle: mockCircles[0],
    likeCount: 5,
    commentCount: 1,
    isLiked: false,
    amount: 175,
    currency: "$",
    circleProgress: {
      current: 2100,
      goal: 5000,
      percentage: 42,
    },
  } as ContributionFeedItem,
  {
    id: "circle-activity-8",
    type: "contribution",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(), // 4d ago
    actor: mockUsers[0],
    circle: mockCircles[0],
    likeCount: 7,
    commentCount: 3,
    isLiked: true,
    amount: 150,
    currency: "$",
    message: "Consistent savings pays off! 💰",
    circleProgress: {
      current: 1925,
      goal: 5000,
      percentage: 39,
    },
  } as ContributionFeedItem,
  {
    id: "circle-activity-9",
    type: "celebration",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 120).toISOString(), // 5d ago
    actor: mockUsers[1],
    circle: mockCircles[0],
    likeCount: 11,
    commentCount: 6,
    isLiked: true,
    content: "Can't wait to relax on the beach with this crew! 🏖️\n\nBest savings circle ever!",
    tags: ["BeachVibes", "SquadGoals"],
  } as CelebrationFeedItem,
  {
    id: "circle-activity-10",
    type: "milestone",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 168).toISOString(), // 7d ago
    actor: mockUsers[2],
    circle: mockCircles[0],
    likeCount: 10,
    commentCount: 8,
    isLiked: false,
    percentage: 25,
    amount: 1250,
    goalAmount: 5000,
    reactions: [
      { emoji: "🎯", count: 10, userReacted: false },
      { emoji: "🚀", count: 6, userReacted: true },
      { emoji: "👏", count: 12, userReacted: false },
    ],
  } as MilestoneFeedItem,
  {
    id: "circle-activity-11",
    type: "contribution",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 192).toISOString(), // 8d ago
    actor: mockUsers[2],
    circle: mockCircles[0],
    likeCount: 4,
    commentCount: 1,
    isLiked: false,
    amount: 150,
    currency: "$",
    circleProgress: {
      current: 1775,
      goal: 5000,
      percentage: 36,
    },
  } as ContributionFeedItem,
  {
    id: "circle-activity-12",
    type: "contribution",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 240).toISOString(), // 10d ago
    actor: mockUsers[1],
    circle: mockCircles[0],
    likeCount: 6,
    commentCount: 2,
    isLiked: true,
    amount: 200,
    currency: "$",
    message: "Feeling good about our progress! 🌴",
    circleProgress: {
      current: 1625,
      goal: 5000,
      percentage: 33,
    },
  } as ContributionFeedItem,
  {
    id: "circle-activity-13",
    type: "member-joined",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 336).toISOString(), // 14d ago
    actor: mockUsers[3],
    circle: mockCircles[0],
    likeCount: 5,
    commentCount: 3,
    isLiked: false,
    welcomeMessage: "So excited to join this circle! Beach here we come! 🏝️",
  } as MemberJoinedFeedItem,
  {
    id: "circle-activity-14",
    type: "contribution",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 408).toISOString(), // 17d ago
    actor: mockUsers[0],
    circle: mockCircles[0],
    likeCount: 5,
    commentCount: 1,
    isLiked: false,
    amount: 150,
    currency: "$",
    circleProgress: {
      current: 1425,
      goal: 5000,
      percentage: 29,
    },
  } as ContributionFeedItem,
  {
    id: "circle-activity-15",
    type: "celebration",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 504).toISOString(), // 21d ago
    actor: mockUsers[0],
    circle: mockCircles[0],
    likeCount: 8,
    commentCount: 5,
    isLiked: true,
    content: "Just created this circle! Who's ready for an epic beach vacation? 🌊☀️",
    tags: ["NewCircle", "BeachBound", "LetsGo"],
  } as CelebrationFeedItem,
];
