import type { User } from "app/context/auth-context";
import type {
  Circle,
  FeedItem,
  UserStats,
  ContributionFeedItem,
  MilestoneFeedItem,
  MemberJoinedFeedItem,
  GoalCompletedFeedItem,
  CelebrationFeedItem,
} from "app/types/feed";

// Mock users
export const mockUsers: User[] = [
  { id: "user1", hasProfile: true, name: "Alex Chen" },
  { id: "user2", hasProfile: true, name: "Sarah Johnson" },
  { id: "user3", hasProfile: true, name: "Mike Rodriguez" },
  { id: "user4", hasProfile: true, name: "Emma Thompson" },
  { id: "user5", hasProfile: true, name: "David Kim" },
];

// Mock circles (user's circles)
export const mockCircles: Circle[] = [
  {
    id: "circle1",
    name: "Beach Vacation Fund",
    emoji: "🏖️",
    goalName: "Beach Vacation",
    goalAmount: 5000,
    currentAmount: 2450,
    memberCount: 5,
    progress: 49,
    members: mockUsers,
    isPublic: true,
    category: "vacation",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 60).toISOString(),
    isActive: true,
  },
  {
    id: "circle2",
    name: "House Down Payment",
    emoji: "🏡",
    goalName: "Down Payment",
    goalAmount: 50000,
    currentAmount: 15000,
    memberCount: 3,
    progress: 30,
    members: mockUsers.slice(0, 3),
    isPublic: false,
    category: "home",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 90).toISOString(),
    isActive: true,
  },
  {
    id: "circle3",
    name: "Gaming Setup",
    emoji: "🎮",
    goalName: "Gaming PC",
    goalAmount: 3000,
    currentAmount: 2800,
    memberCount: 4,
    progress: 93,
    members: mockUsers.slice(0, 4),
    isPublic: true,
    category: "technology",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    isActive: true,
  },
];

// Mock public circles for explore page
export const mockPublicCircles: Circle[] = [
  ...mockCircles.filter((c) => c.isPublic),
  {
    id: "circle4",
    name: "European Adventure",
    emoji: "✈️",
    goalName: "Europe Trip",
    goalAmount: 8000,
    currentAmount: 6400,
    memberCount: 6,
    progress: 80,
    members: mockUsers.slice(0, 3),
    isPublic: true,
    category: "vacation",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 45).toISOString(),
    isActive: true,
  },
  {
    id: "circle5",
    name: "Master's Degree Fund",
    emoji: "🎓",
    goalName: "Education",
    goalAmount: 25000,
    currentAmount: 8500,
    memberCount: 2,
    progress: 34,
    members: mockUsers.slice(0, 2),
    isPublic: true,
    category: "education",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 120).toISOString(),
    isActive: true,
  },
  {
    id: "circle6",
    name: "Wedding Celebration",
    emoji: "💍",
    goalName: "Dream Wedding",
    goalAmount: 15000,
    currentAmount: 12000,
    memberCount: 8,
    progress: 80,
    members: mockUsers.slice(0, 3),
    isPublic: true,
    category: "events",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 180).toISOString(),
    isActive: true,
  },
  {
    id: "circle7",
    name: "Youth Mentorship Program",
    emoji: "🎯",
    goalName: "Program Development",
    goalAmount: 5000,
    currentAmount: 4650,
    memberCount: 19,
    progress: 93,
    members: mockUsers.slice(0, 3),
    isPublic: true,
    category: "education",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 25).toISOString(),
    isActive: true,
  },
  {
    id: "circle8",
    name: "Home Renovation",
    emoji: "🔨",
    goalName: "Kitchen Remodel",
    goalAmount: 30000,
    currentAmount: 9000,
    memberCount: 2,
    progress: 30,
    members: mockUsers.slice(0, 2),
    isPublic: true,
    category: "home",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 75).toISOString(),
    isActive: true,
  },
  {
    id: "circle9",
    name: "Community Garden Project",
    emoji: "🌱",
    goalName: "Urban Garden Supplies",
    goalAmount: 3500,
    currentAmount: 2450,
    memberCount: 12,
    progress: 70,
    members: mockUsers.slice(0, 3),
    isPublic: true,
    category: "other",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 20).toISOString(),
    isActive: true,
  },
  {
    id: "circle10",
    name: "Tokyo Trip 2026",
    emoji: "🗾",
    goalName: "Japan Vacation",
    goalAmount: 6000,
    currentAmount: 2100,
    memberCount: 4,
    progress: 35,
    members: mockUsers.slice(0, 3),
    isPublic: true,
    category: "vacation",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 40).toISOString(),
    isActive: true,
  },
  {
    id: "circle11",
    name: "Coding Bootcamp",
    emoji: "👨‍💻",
    goalName: "Career Training",
    goalAmount: 12000,
    currentAmount: 3600,
    memberCount: 2,
    progress: 30,
    members: mockUsers.slice(0, 2),
    isPublic: true,
    category: "education",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 55).toISOString(),
    isActive: true,
  },
  {
    id: "circle12",
    name: "Music Festival Squad",
    emoji: "🎵",
    goalName: "Festival Tickets",
    goalAmount: 3000,
    currentAmount: 2700,
    memberCount: 10,
    progress: 90,
    members: mockUsers.slice(0, 3),
    isPublic: true,
    category: "events",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15).toISOString(),
    isActive: true,
  },
  {
    id: "circle13",
    name: "Community Center Renovation",
    emoji: "🏛️",
    goalName: "Youth Center Repairs",
    goalAmount: 8000,
    currentAmount: 3200,
    memberCount: 18,
    progress: 40,
    members: mockUsers.slice(0, 3),
    isPublic: true,
    category: "other",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    isActive: true,
  },
  {
    id: "circle14",
    name: "Local Animal Shelter",
    emoji: "🐕",
    goalName: "Shelter Support Fund",
    goalAmount: 5000,
    currentAmount: 3750,
    memberCount: 25,
    progress: 75,
    members: mockUsers.slice(0, 3),
    isPublic: true,
    category: "other",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 35).toISOString(),
    isActive: true,
  },
  {
    id: "circle15",
    name: "School Supplies Drive",
    emoji: "✏️",
    goalName: "Back-to-School Donations",
    goalAmount: 2500,
    currentAmount: 2100,
    memberCount: 15,
    progress: 84,
    members: mockUsers.slice(0, 3),
    isPublic: true,
    category: "education",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 50).toISOString(),
    isActive: true,
  },
  {
    id: "circle16",
    name: "Youth Sports Program",
    emoji: "⚽",
    goalName: "Equipment & Uniforms",
    goalAmount: 4000,
    currentAmount: 3800,
    memberCount: 22,
    progress: 95,
    members: mockUsers.slice(0, 3),
    isPublic: true,
    category: "other",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 12).toISOString(),
    isActive: true,
  },
  {
    id: "circle17",
    name: "Tree Planting Initiative",
    emoji: "🌳",
    goalName: "Urban Reforestation",
    goalAmount: 6000,
    currentAmount: 2400,
    memberCount: 31,
    progress: 40,
    members: mockUsers.slice(0, 3),
    isPublic: true,
    category: "other",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 22).toISOString(),
    isActive: true,
  },
  {
    id: "circle18",
    name: "Free Meal Program",
    emoji: "🍲",
    goalName: "Community Kitchen",
    goalAmount: 7500,
    currentAmount: 4500,
    memberCount: 28,
    progress: 60,
    members: mockUsers.slice(0, 3),
    isPublic: true,
    category: "other",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    isActive: true,
  },
  {
    id: "circle19",
    name: "Medical Fund for Friend",
    emoji: "💊",
    goalName: "Treatment Support",
    goalAmount: 10000,
    currentAmount: 7500,
    memberCount: 42,
    progress: 75,
    members: mockUsers.slice(0, 3),
    isPublic: true,
    category: "other",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 28).toISOString(),
    isActive: true,
  },
  {
    id: "circle20",
    name: "Local Library Books",
    emoji: "📚",
    goalName: "Children's Section",
    goalAmount: 3000,
    currentAmount: 600,
    memberCount: 14,
    progress: 20,
    members: mockUsers.slice(0, 3),
    isPublic: true,
    category: "education",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
    isActive: true,
  },
];

// Mock user stats
export const mockUserStats: UserStats = {
  totalSaved: 2450,
  activeCircles: 3,
  goalsCompleted: 2,
  totalGoals: 5,
  monthlyTrend: 12,
};

// Mock feed items
export const mockFeedItems: FeedItem[] = [
  {
    id: "feed1",
    type: "contribution",
    timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(), // 30 mins ago
    actor: mockUsers[0],
    circle: mockCircles[0],
    likeCount: 5,
    commentCount: 2,
    isLiked: false,
    amount: 150,
    currency: "$",
    message: "Keep it up! Almost halfway to our vacation goal.",
    circleProgress: {
      current: 2450,
      goal: 5000,
      percentage: 49,
    },
  } as ContributionFeedItem,
  {
    id: "feed2",
    type: "milestone",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(), // 2 hours ago
    actor: mockUsers[1],
    circle: mockCircles[0],
    likeCount: 12,
    commentCount: 8,
    isLiked: true,
    percentage: 50,
    amount: 2500,
    goalAmount: 5000,
    reactions: [
      { emoji: "🎉", count: 12, userReacted: true },
      { emoji: "🔥", count: 8, userReacted: false },
      { emoji: "❤️", count: 15, userReacted: true },
    ],
  } as MilestoneFeedItem,
  {
    id: "feed3",
    type: "member-joined",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(), // 5 hours ago
    actor: mockUsers[4],
    circle: mockCircles[1],
    likeCount: 3,
    commentCount: 1,
    isLiked: false,
    welcomeMessage: "Welcome to the circle! Let's achieve our savings goals together.",
  } as MemberJoinedFeedItem,
  {
    id: "feed4",
    type: "contribution",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(), // 8 hours ago
    actor: mockUsers[2],
    circle: mockCircles[2],
    likeCount: 7,
    commentCount: 3,
    isLiked: false,
    amount: 200,
    currency: "$",
    message: "So close to our gaming setup goal!",
    circleProgress: {
      current: 2800,
      goal: 3000,
      percentage: 93,
    },
  } as ContributionFeedItem,
  {
    id: "feed5",
    type: "goal-completed",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(), // 1 day ago
    actor: mockUsers[0],
    circle: {
      ...mockCircles[2],
      goalName: "Weekend Trip",
      goalAmount: 1500,
      currentAmount: 1500,
    },
    likeCount: 24,
    commentCount: 15,
    isLiked: true,
    totalSaved: 1500,
    daysToComplete: 45,
  } as GoalCompletedFeedItem,
  {
    id: "feed6",
    type: "contribution",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(), // 2 days ago
    actor: mockUsers[3],
    circle: mockCircles[1],
    likeCount: 4,
    commentCount: 1,
    isLiked: false,
    amount: 500,
    currency: "$",
    circleProgress: {
      current: 15000,
      goal: 50000,
      percentage: 30,
    },
  } as ContributionFeedItem,
  {
    id: "feed7",
    type: "celebration",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(), // 4 hours ago
    actor: mockUsers[1],
    circle: mockCircles[0],
    likeCount: 8,
    commentCount: 5,
    isLiked: false,
    content: "Just made my first contribution! Feels great to be saving with friends 🎉\n\nWho else is excited about our beach trip?",
    tags: ["SavingsGoals", "BeachBound", "TeamWork"],
  } as CelebrationFeedItem,
  {
    id: "feed8",
    type: "celebration",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(), // 12 hours ago
    actor: mockUsers[2],
    circle: mockCircles[0],
    likeCount: 15,
    commentCount: 9,
    isLiked: true,
    content: "Halfway there team! Let's keep the momentum going 💪\n\nI can already feel the sand between my toes!",
    imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
    imageAlt: "Beautiful beach with clear blue water and white sand",
    tags: ["HalfwayThere", "BeachVibes", "VacationMode"],
  } as CelebrationFeedItem,
  {
    id: "feed9",
    type: "celebration",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(), // 20 hours ago
    actor: mockUsers[4],
    circle: mockCircles[2],
    likeCount: 6,
    commentCount: 3,
    isLiked: false,
    content: "Who else is hyped for our gaming setup? Almost there! 🎮\n\nCan't wait to stream with the squad!",
    tags: ["GamingSquad", "AlmostThere"],
  } as CelebrationFeedItem,
  {
    id: "feed10",
    type: "celebration",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(), // 3 days ago
    actor: mockUsers[0],
    circle: mockCircles[1],
    likeCount: 11,
    commentCount: 7,
    isLiked: true,
    content: "Small wins add up! Every dollar counts 💰\n\nStaying consistent is the key to reaching our house down payment goal. Let's do this!",
    tags: ["ConsistencyIsKey", "SmallWins", "DreamHome"],
  } as CelebrationFeedItem,
];
